version: 0.1

phases:
  install:
    commands:
      - gem install bundler jekyll
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - cd jekyll-clouddevopslearningblog
      - jekyll build
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - cd jekyll-clouddevopslearningblog
      - aws s3 sync _site s3://theclouddevopslearningblog.com/ --delete  
      - echo "******** Invalidating CDN ********"
      - aws cloudfront create-invalidation --distribution-id E5CSONWGEIVIX --paths "/*"
      