# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

comments: true

bannerimage: /media/bannerimage.png

site:
  url:  'https://theclouddevopslearningblog.com'

texture:
  title: The Cloud DevOps Learning Blog
  tagline:   "For The Cloud & DevOps I Don't Yet Know."
  date_format: "%-d %b %Y"
  style: [black]
  
  showNav: true
  navigation:
    - title: Home
      url: /
    - title: Blog
      url: /blog/
      dropdown: posts   # ← only this item gets a posts dropdown
    - title: About
      url: /about/
    - title: "Comment Policy"
      url: /comment-policy/
    - title: Résumé
      url: https://s3.ap-southeast-2.amazonaws.com/theclouddevopslearningblog.com/media/Simon+Mackinnon.pdf
      newtab: true

  analytics_id: 'UA-167551328-1'

  disqus_shortname: 'the-cloud-devops-learning-blog'

  social_links:
    github:  simonmackinnon
    linkedIn: in/simonmackinnon # format: locale/username

# Build settings
#theme: minima
theme: texture

plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  

title: The Cloud DevOps Learning Blog
tagline:   "For The Cloud & DevOps I Don't Yet Know."

github_username: simonmackinnon   # change to yours
rss: /feed.xml                     # if you generate a feed



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
